name: 生成规则文件
on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * *"
jobs:
  build:
    name: 生成规则文件
    runs-on: ubuntu-latest
    steps:
    - name: 下载规则文件生成工具
      run: |
        curl -so gfwlist2dnsmasq.sh https://raw.githubusercontent.com/xilaochengv/Rule/main/gfwlist2dnsmasq.sh
        curl -so v2ipdat https://raw.githubusercontent.com/xilaochengv/Rule/main/v2ipdat
        curl -so v2sitedat https://raw.githubusercontent.com/xilaochengv/Rule/main/v2sitedat
        mkdir ips sites
        chmod 755 gfwlist2dnsmasq.sh v2ipdat v2sitedat
    - name: 下载geoip规则
      run: |
        curl -s http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest > /tmp/ips
        cat /tmp/ips | awk -F '|' '/CN/&&/ipv4/ {print $4 "/" 32-log($5)/log(2)}' > ips/cn
        cat /tmp/ips | awk -F '|' '/CN/&&/ipv4/ {print $4 "/" 32-log($5)/log(2)}' > cn_ip.txt
        cat /tmp/ips | awk -F '|' '/CN/&&/ipv6/ {print $4 "/" $5}' >> ips/cn
        cat /tmp/ips | awk -F '|' '/CN/&&/ipv6/ {print $4 "/" $5}' > cn_ipv6.txt
        curl -s https://www.gstatic.com/ipranges/goog.json | jq --raw-output '.prefixes[].ipv4Prefix,.prefixes[].ipv6Prefix | select(. != null)' > ips/google
        curl -s https://www.gstatic.com/ipranges/cloud.json | jq --raw-output '.prefixes[].ipv4Prefix,.prefixes[].ipv6Prefix | select(. != null)' >> ips/google
        curl -s https://core.telegram.org/resources/cidr.txt > ips/telegram
        for line in $(awk 'a[$0]++ {print NR}' ips/google | sort -r);do [ "$line" ] && sed -i "${line}d" ips/google;done
        for list in $(ls ips);do echo -n "$(cat ips/$list)" > ips/$list;done
    - name: 下载geosite规则
      run: |
        curl -s https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf | awk -F / '{print $2}' > sites/cn
        curl -s https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt > sites/gfw
        ./gfwlist2dnsmasq.sh -o sites/gfw &> /dev/null && sed -i 's#.*=/##;s#/.*##' sites/gfw
        rules="apple bahamut epicgames google microsoft netflix ookla-speedtest rockstar steam telegram youtube"
        for rule in $rules;do curl -s https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/$rule > sites/$rule;done
        for rule in $(ls sites);do sed -i 's/#.*//' sites/$rule;echo -n "$(cat sites/$rule | grep '[^^$]')" > sites/$rule;done
    - name: 生成文件
      run: |
        ./v2ipdat
        ./v2sitedat
        echo "自用规则文件" > body
        rules="" && for rule in $(ls ips);do rules="$rules$(echo -n "$rule ")";done
        echo "geoip可用：$(echo $rules | sed 's/ /,/g')" >> body
        rules="" && for rule in $(ls sites);do rules="$rules$(echo -n "$rule ")";done
        echo "geosite可用：$(echo $rules | sed 's/ /,/g')" >> body        
    - name: 上传到Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            cn_ip.txt
            cn_ipv6.txt
            geoip.dat
            geosite.dat
          tag_name: Latest
          body_path: body
