name: 生成规则文件
on:
  workflow_dispatch:
  schedule:
    - cron: "30 21 * * *"
jobs:
  build:
    name: 生成规则文件
    runs-on: ubuntu-latest
    steps:
    - name: 下载规则文件生成工具
      run: |
        curl -so gfwlist2dnsmasq.sh https://raw.githubusercontent.com/xilaochengv/Rule/main/gfwlist2dnsmasq.sh
        curl -so v2ipdat https://raw.githubusercontent.com/xilaochengv/Rule/main/v2ipdat
        curl -so v2sitedat https://raw.githubusercontent.com/xilaochengv/Rule/main/v2sitedat
        mkdir ips sites
        chmod 755 gfwlist2dnsmasq.sh v2ipdat v2sitedat
    - name: 下载geoip规则
      run: |
        curl -s http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest > /tmp/ips
        cat /tmp/ips | awk -F '|' '/CN/&&/ipv4/ {print $4 "/" 32-log($5)/log(2)}' > ips/cn
        cat /tmp/ips | awk -F '|' '/CN/&&/ipv4/ {print $4 "/" 32-log($5)/log(2)}' > cn_ip.txt
        cat /tmp/ips | awk -F '|' '/CN/&&/ipv6/ {print $4 "/" $5}' >> ips/cn
        cat /tmp/ips | awk -F '|' '/CN/&&/ipv6/ {print $4 "/" $5}' > cn_ipv6.txt
        curl -s https://www.gstatic.com/ipranges/goog.json | jq --raw-output '.prefixes[].ipv4Prefix,.prefixes[].ipv6Prefix | select(. != null)' > ips/google
        curl -s https://www.gstatic.com/ipranges/cloud.json | jq --raw-output '.prefixes[].ipv4Prefix,.prefixes[].ipv6Prefix | select(. != null)' >> ips/google
        #curl -s https://raw.githubusercontent.com/lingchenzi/app/main/Netflix_IP > ips/netflix
        curl -s https://core.telegram.org/resources/cidr.txt > ips/telegram
        curl -skm 10 https://trackerslist.com/all.txt | awk -F / '{print $3}' | grep -oE '[0-9.]{7,15}|[0-9a-f:]{10,39}' | grep -E '\.|:' | grep -vE '^\.|\.$' | awk '!a[$0]++' > ips/tracker
        curl -skm 10 https://raw.githubusercontent.com/Tunglies/TrackersList/main/all.txt | awk -F / '{print $3}' | grep -vE '[a-z]$|[a-z]:' | grep -oE '^[0-9.]{7,15}|^[[0-9a-f:]{10,39}' | sed 's/\[//' | awk '!a[$0]++' >> ips/tracker
        curl -skm 10 https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt | awk -F / '{print $3}' | grep -vE '[a-z]$|[a-z]:' | grep -oE '^[0-9.]{7,15}|^[[0-9a-f:]{10,39}' | sed 's/\[//' | awk '!a[$0]++' >> ips/tracker
        curl -skm 10 'https://newtrackon.com/api/stable?include_ipv4_only_trackers=1&include_ipv6_only_trackers=1' | awk -F / '{print $3}' | grep -vE '[a-z]$|[a-z]:' | grep -oE '^[0-9.]{7,15}|^[[0-9a-f:]{10,39}' | sed 's/\[//' | awk '!a[$0]++' >> ips/tracker
        awk '!a[$0]++' ips/tracker > ips/trackers
        rm -f ips/tracker
        for line in $(awk 'a[$0]++ {print NR}' ips/google | sort -r);do [ "$line" ] && sed -i "${line}d" ips/google;done
        for list in $(ls ips);do echo -n "$(cat ips/$list)" > ips/$list;done
    - name: 下载geosite规则
      run: |
        curl -s https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf | awk -F / '{print $2}' > sites/cn
        curl -s https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt > sites/gfw
        ./gfwlist2dnsmasq.sh -o sites/gfw &> /dev/null && sed -i 's#.*=/##;s#/.*##' sites/gfw
        curl -skm 10 https://trackerslist.com/all.txt | awk -F / '{print $3}' | grep [a-z] | grep -v ] | sed 's/:.*//' | awk '!a[$0]++' > sites/tracker
        curl -skm 10 https://raw.githubusercontent.com/Tunglies/TrackersList/main/all.txt | awk -F / '{print $3}' | grep [a-z] | grep -v ] | sed 's/:.*//' | awk '!a[$0]++' >> sites/tracker
        curl -skm 10 https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt | awk -F / '{print $3}' | grep [a-z] | grep -v ] | sed 's/:.*//' | awk '!a[$0]++' >> sites/tracker
        curl -skm 10 'https://newtrackon.com/api/stable?include_ipv4_only_trackers=1&include_ipv6_only_trackers=1' | awk -F / '{print $3}' | grep [a-z] | grep -v ] | sed 's/:.*//' | awk '!a[$0]++' >> sites/tracker
        awk '!a[$0]++' sites/tracker > sites/trackers
        rm -f sites/tracker
        rules="apple bahamut epicgames google microsoft ookla-speedtest steam telegram youtube"
        for rule in $rules;do curl -s https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/$rule > sites/$rule;done
        for rule in $(ls sites);do sed -i 's/#.*//;s/ //g' sites/$rule;echo -n "$(cat sites/$rule | grep '[^^$]')" > sites/$rule;done
    - name: 生成文件
      run: |
        curl -skm 10 https://trackerslist.com/all.txt > trackers
        curl -skm 10 https://raw.githubusercontent.com/Tunglies/TrackersList/main/all.txt >> trackers
        curl -skm 10 https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt >> trackers
        curl -skm 10 'https://newtrackon.com/api/stable?include_ipv4_only_trackers=1&include_ipv6_only_trackers=1' >> trackers
        awk '!a[$0]++' trackers > trackers_all
        ./v2ipdat
        ./v2sitedat
        echo "自用规则文件" > body
        rules="" && for rule in $(ls ips);do rules="$rules$(echo -n "$rule ")";done
        echo "geoip可用：$(echo $rules | sed 's/ /,/g')" >> body
        rules="" && for rule in $(ls sites);do rules="$rules$(echo -n "$rule ")";done
        echo "geosite可用：$(echo $rules | sed 's/ /,/g')" >> body
    - name: 上传到Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            cn_ip.txt
            cn_ipv6.txt
            geoip.dat
            geosite.dat
            trackers_all
          tag_name: Latest
          body_path: body
